import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";

import "./globals.css";
import ReactQueryClientProvider from "../components/ReactQueryClientProvider";
import { AuthProvider } from "@/contexts/AuthContext";
import FavoriteProviderWrapper from "@/components/FavoriteProviderWrapper";
import KakaoScriptLoader from "../components/KakaoScriptLoader";
import { Header } from "@/components/Header";
import { BottomNavigation } from "@/components/BottomNavigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/fonts/SUIT-Regular.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/SUIT-Medium.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.8/kakao.min.js"
        />
      </head>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <KakaoScriptLoader />
        <ReactQueryClientProvider>
          <AuthProvider>
            <FavoriteProviderWrapper>
              <div className="min-h-screen flex flex-col">
                <Header />
                <main className="flex-1 pb-16">
                  {children}
                </main>
                <BottomNavigation />
              </div>
            </FavoriteProviderWrapper>
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
