import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import "@/index.css";
import ReactQueryClientProvider from "../components/ReactQueryClientProvider";
import { AuthProvider } from "@/contexts/AuthContext";
import KakaoScriptLoader from "../components/KakaoScriptLoader";
import { Header } from "@/components/Header";
import { BottomNavigation } from "@/components/BottomNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.8/kakao.min.js"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <KakaoScriptLoader />
        <ReactQueryClientProvider>
          <AuthProvider>
            <div className="min-h-screen flex flex-col">
              <Header />
              <main className="flex-1 pb-16">
                {children}
              </main>
              <BottomNavigation />
            </div>
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
